---
- include_role:
    name: confluent.common
  when: not common_role_completed|bool

- name: Gather OS Facts
  setup:
    # Only gathers items in list, filters out the rest
    filter: "{{item}}"
    gather_subset:
      - '!all'
  loop:
    - ansible_os_family
    - ansible_fqdn

- name: Install the Kafka Broker Packages
  yum:
    name: "{{item}}{{confluent_package_redhat_suffix}}"
    state: latest
  loop: "{{kafka_broker_packages}}"
  when:
    - ansible_os_family == "RedHat"
    - installation_method == "package"

- name: Install the Kafka Broker Packages
  apt:
    name: "{{item}}{{confluent_package_debian_suffix}}"
  loop: "{{kafka_broker_packages}}"
  when:
    - ansible_os_family == "Debian"
    - installation_method == "package"

- name: Kafka Broker group
  group:
    name: "{{kafka_broker_group}}"

- name: Kafka Broker user
  user:
    name: "{{kafka_broker_user}}"
    comment: "Kafka User"
    system: true
    group: "{{kafka_broker_group}}"
  when:
    - hardened_env == false

- name: Ensure SystemD directory exists - User
  file:
    path: "{{kafka_broker.systemd_file | dirname}}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    state: directory
    mode: 0740
  when:
    - hardened_env == true

# Archive File deployments need to create SystemD service units
# Copy the tarball's systemd service to the system
- name: Copy Kafka Broker Service from archive file to system
  copy:
    src: "{{binary_base_path}}/lib/systemd/system/{{kafka_broker.systemd_file|basename}}"
    remote_src: true
    dest: "{{kafka_broker.systemd_file}}"
    mode: 0644
    force: true
  when: installation_method == "archive"

- include_role:
    name: confluent.ssl
  vars:
    truststore_storepass: "{{kafka_broker_truststore_storepass}}"
    truststore_path: "{{kafka_broker_truststore_path}}"
    keystore_path: "{{kafka_broker_keystore_path}}"
    keystore_storepass: "{{kafka_broker_keystore_storepass}}"
    keystore_keypass: "{{kafka_broker_keystore_keypass}}"
    service_name: kafka_broker
    user: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    hostnames: "{{ ([inventory_hostname, ansible_fqdn, ansible_host, ansible_ssh_host] + kafka_broker_listeners | get_hostnames(inventory_hostname)) | unique }}"
    ca_cert_path: "{{kafka_broker_ca_cert_path}}"
    cert_path: "{{kafka_broker_cert_path}}"
    key_path: "{{kafka_broker_key_path}}"
    export_certs: "{{kafka_broker_export_certs}}"
  when: >
    zookeeper_ssl_enabled|bool or
    kafka_broker_listeners | ssl_required(ssl_enabled) or
    kafka_broker_rest_ssl_enabled|bool or
    mds_broker_listener.ssl_enabled|bool or
    mds_tls_enabled|bool or
    schema_registry_ssl_enabled|bool

- include_tasks: rbac.yml
  when: rbac_enabled|bool

- name: Configure Kerberos
  include_role:
    name: confluent.kerberos
  vars:
    kerberos_group: "{{kafka_broker_group}}"
    kerberos_user: "{{kafka_broker_user}}"
    kerberos_keytab_path: "{{kafka_broker_kerberos_keytab_path}}"
    kerberos_keytab_destination_path: "{{kafka_broker_keytab_path}}"
    kerberos_handler: "restart kafka"
  when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms or zookeeper_sasl_protocol == 'kerberos' or mds_broker_listener.sasl_protocol =='kerberos'"

- name: Copy Custom Kafka Files
  include_tasks: ../../tasks/copy_files.yml
  vars:
    copy_files: "{{kafka_broker_copy_files}}"
    user: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: kafka_broker_copy_files | length > 0

- name: Set Permissions on Data Dirs
  file:
    path: "{{item}}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    state: directory
    mode: 0750
  with_items: "{{ kafka_broker_final_properties['log.dirs'].split(',') }}"

- name: Set Permissions on Data Dir files
  file:
    path: "{{item}}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    recurse: true
  with_items: "{{ kafka_broker_final_properties['log.dirs'].split(',') }}"

- name: Create Kafka Broker Config directory
  file:
    path: "{{ kafka_broker.config_file | dirname }}"
    state: directory
    mode: 0750
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"

- name: Create Kafka Broker Config
  template:
    src: server.properties.j2
    dest: "{{kafka_broker.config_file}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  notify: restart kafka

- name: Create Logs Directory
  file:
    path: "{{kafka_broker.appender_log_path}}"
    state: directory
    group: "{{kafka_broker_group}}"
    owner: "{{kafka_broker_user}}"
    mode: 0770

- name: Create log4j Directory
  file:
    path: "{{kafka_broker.log4j_file | dirname}}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    state: directory
    mode: 0750

- name: Create Kafka Broker log4j Config
  template:
    src: kafka_server_log4j.properties.j2
    dest: "{{kafka_broker.log4j_file}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: kafka_broker_custom_log4j|bool
  notify: restart kafka

- name: Create Kafka Broker Jolokia Config
  template:
    src: kafka_jolokia.properties.j2
    dest: "{{kafka_broker_jolokia_config}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: kafka_broker_jolokia_enabled|bool
  notify: restart kafka

- name: Create Kafka Broker Jaas Config
  template:
    src: kafka_server_jaas.conf.j2
    dest: "{{kafka_broker.jaas_file}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: "'GSSAPI' in kafka_broker_sasl_enabled_mechanisms or zookeeper_sasl_protocol in ['kerberos', 'digest']"
  notify: restart kafka

- name: Create SCRAM Users
  shell: |
    kafka-configs --zookeeper localhost:{{zookeeper_final_properties.clientPort}} --alter \
      --add-config 'SCRAM-SHA-512=[password={{ item.value['password'] }}]' \
      --entity-type users --entity-name {{ item.value['principal'] }}
  loop: "{{ sasl_scram_users|dict2items }}"
  delegate_to: "{{ groups['zookeeper'][0] }}"
  run_once: true
  when: "'SCRAM-SHA-512' in kafka_broker_sasl_enabled_mechanisms"

- name: Deploy JMX Exporter Config File
  copy:
    src: "kafka.yml"
    dest: "{{kafka_broker_jmxexporter_config_path}}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  when: kafka_broker_jmxexporter_enabled|bool

- name: Create Service Override Directory
  file:
    path: "{{kafka_broker.systemd_override | dirname }}"
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
    state: directory
    mode: 0740

- name: Enable Secrets Protection
  include_tasks: ../../tasks/secrets_protection.yml
  vars:
    encrypt_passwords: "{{ kafka_broker_secrets_protection_encrypt_passwords }}"
    properties: "{{ kafka_broker_secrets_protection_encrypt_properties }}"
    config_path: "{{ kafka_broker.config_file }}"
  when: kafka_broker_secrets_protection_enabled|bool

- name: Write Service Overrides
  template:
    src: override.conf.j2
    dest: "{{ kafka_broker.systemd_override }}"
    mode: 0640
    owner: "{{kafka_broker_user}}"
    group: "{{kafka_broker_group}}"
  notify: restart kafka

- name: Tune virtual memory settings
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: "{{ kafka_broker_sysctl_file }}"
    reload: true
  with_dict: "{{ kafka_broker_sysctl }}"
  when:
    - hardened_env == false

- name: Certs were Updated - Trigger Restart
  command: /bin/true
  notify: restart kafka
  when: certs_updated|bool

- meta: flush_handlers

- name: Kafka Started
  systemd:
    name: "{{kafka_broker_service_name}}"
    enabled: true
    state: started
  tags:
    - systemd
  when:
    - hardened_env == false

- name: Kafka Started - User
  systemd:
    name: "{{kafka_broker_service_name}}"
    enabled: true
    state: started
    scope: user
  tags:
    - systemd
  when:
    - hardened_env == true

- name: Wait for Health Checks to Complete
  include_tasks: health_check.yml
  when:
    - kafka_broker_health_checks_enabled|bool
    - not ansible_check_mode

- include_tasks: rbac_rolebindings.yml
  when: kafka_broker_additional_system_admins|length > 0
