---
- name: Restart Kafka
  systemd:
    daemon_reload: true
    name: "{{kafka_broker_service_name}}"
    state: restarted
  when:
    - hardened_env == false

- name: Restart Kafka - User
  systemd:
    daemon_reload: true
    name: "{{kafka_broker_service_name}}"
    state: restarted
    scope: user
  when:
    - hardened_env == true

- name: Wait for Health Checks to Complete
  include_tasks: health_check.yml
  when:
    - kafka_broker_health_checks_enabled|bool
    - not ansible_check_mode
